menu:
    Home: /
    Categories: /categories/
    Archive: /archives/
    App: /app/
    GitHub: https://github.com/hellomafei

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2018

# Category
categories: /categories
app: /app
